# Generated by Django 2.1.7 on 2019-03-08 03:04

import authorapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(upload_to='photos', validators=[authorapp.validators.file_size_validator]),
        ),
    ]
